# Generated by Django 2.1 on 2020-06-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200604_1547'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='damage',
            table='hotel_rooms_damages',
        ),
    ]
